BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Posts";
CREATE TABLE IF NOT EXISTS "Posts" (
	"ID"	TEXT NOT NULL UNIQUE,
	"PostedDateTime"	TEXT NOT NULL,
	"NamedBlobID"	TEXT NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("NamedBlobID") REFERENCES "NamedBlobs"("ID")
);
DROP TABLE IF EXISTS "PostTags";
CREATE TABLE IF NOT EXISTS "PostTags" (
	"PostID"	TEXT NOT NULL,
	"TagID"	TEXT NOT NULL,
	FOREIGN KEY("PostID") REFERENCES "Posts"("ID"),
	FOREIGN KEY("TagID") REFERENCES "Tags"("ID")
);
DROP TABLE IF EXISTS "Tags";
CREATE TABLE IF NOT EXISTS "Tags" (
	"ID"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("ID")
);
DROP TABLE IF EXISTS "NamedBlobs";
CREATE TABLE IF NOT EXISTS "NamedBlobs" (
	"ID"	TEXT NOT NULL UNIQUE,
	"Data"	BLOB,
	PRIMARY KEY("ID")
);
COMMIT;
